version: "3.9"

services:
  postgres:
    container_name: volamail-postgres
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - volamail_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=volamail
      - POSTGRES_PASSWORD=volamail
      - POSTGRES_DB=volamail_db

volumes:
  volamail_pg_data:
