/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "EmailNotificationsTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "Web": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
  }
}
