version: "3.9"

services:
  postgres:
    container_name: volamail-postgres
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=volamail
      - POSTGRES_PASSWORD=volamail
      - POSTGRES_DB=volamail_db
