name: Deploy to Staging

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - develop

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest

      - name: Pull Environment Variables
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Run migrations
        run: pnpm db migrate
        working-directory: apps/app
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy project to Staging
        run: |
          url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" ${{ vars.STAGING_DOMAIN }}
