name: Deploy to Production

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deploy-production:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 3600
          aws-region: eu-central-1

      - name: Install dependencies
        run: bun install

      - name: Set SST secrets
        run: |
          bun run sst secret set DatabaseUrl ${{ secrets.DATABASE_URL }} --stage production
          bun run sst secret set GithubClientSecret ${{ secrets.GH_CLIENT_SECRET }} --stage production
          bun run sst secret set StripeSecretKey ${{ secrets.STRIPE_SECRET_KEY }} --stage production
          bun run sst secret set StripeWebhookSecret ${{ secrets.STRIPE_WEBHOOK_SECRET }} --stage production

      - name: Deploy to Production
        run: bun run sst deploy --stage production
        env:
          ACM_CERTIFICATE_ARN: ${{ vars.ACM_CERTIFICATE_ARN }}
          VITE_SELF_HOSTED: "false"
          VITE_DOMAIN: ${{ vars.DOMAIN }}
          VITE_NOREPLY_EMAIL: ${{ vars.NOREPLY_EMAIL }}
          VITE_SUPPORT_EMAIL: ${{ vars.SUPPORT_EMAIL }}
          VITE_GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          VITE_STRIPE_PRO_PLAN_PRICE_ID: ${{ vars.STRIPE_PRO_PLAN_PRICE_ID }}

      - name: Run DB migrations
        run: bun run drizzle-kit migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
